backend:
  name: github
  repo: veraandcompany/docs-poc # Asegúrate de que este es tu repositorio de GitHub
  branch: main

media_folder: static/uploads
public_folder: /uploads
publish_mode: editorial_workflow

collections:
  - name: docs
    label: Docs
    folder: docs
    create: true
    slug: "{{title | slugify}}"
    nested:
      depth: 100
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - { label: "Slug", name: "slug", widget: "hidden", default: "{{filename}}" }
    meta: { path: {label: 'Path', widget: 'string', index_file: slug }}
